#!/usr/bin/env python3

# This is our main dictionary for languages.

from typing import List, NamedTuple, Optional

MAIN_LANGUAGES = {
    "aa": {
        "supported": False,
        "name": "Afar",
        "language_code_3": "aar",
        "alternate_names": ["Afaraf"],
        "thanks": "Gadda ge",
    },
    "ab": {
        "supported": False,
        "name": "Abkhaz",
        "language_code_3": "abk",
        "alternate_names": ["Abxazo", "Abkhazian"],
        "thanks": "Иҭабуп",
    },
    "acm": {
        "supported": True,
        "name": "Mesopotamian Arabic",
        "language_code_3": "acm",
        "alternate_names": ["Baghdadi", "Furati"],
    },
    "ae": {
        "supported": False,
        "name": "Avestan",
        "language_code_3": "ave",
        "alternate_names": ["Avesta"],
        "subreddits": ["r/avestan"],
    },
    "aeb": {
        "supported": True,
        "name": "Tunisian Arabic",
        "language_code_3": "aeb",
        "alternate_names": ["Tunisian Darija"],
    },
    "af": {
        "supported": True,
        "name": "Afrikaans",
        "language_code_3": "afr",
        "alternate_names": None,
        "countries_default": "ZA",
        "countries_associated": ["NA"],
        "subreddits": ["r/afrikaans"],
        "thanks": "Dankie",
    },
    "ak": {
        "supported": False,
        "name": "Akan",
        "language_code_3": "aka",
        "alternate_names": None,
        "thanks": "Meda wo ase",
    },
    "am": {
        "supported": True,
        "name": "Amharic",
        "language_code_3": "amh",
        "alternate_names": [
            "Ethiopian",
            "Ethiopia",
            "Ethopian",
            "Ethiopic",
            "Abyssinian",
            "Amarigna",
            "Amarinya",
            "Amhara",
        ],
        "countries_default": "ET",
        "subreddits": ["r/amharic"],
        "thanks": "አመሰግናለሁ",
    },
    "an": {
        "supported": False,
        "name": "Aragonese",
        "language_code_3": "arg",
        "alternate_names": None,
        "thanks": "Gracias",
    },
    "ang": {
        "supported": True,
        "name": "Anglo-Saxon",
        "language_code_3": "ang",
        "alternate_names": ["Old English", "Anglo Saxon", "Anglosaxon", "Anglisc"],
        "thanks": "Þancas",
    },
    "app": {
        "language_code_3": "app",
        "name": "App",
        "supported": True,
        "alternate_names": None,
    },
    "ar": {
        "supported": True,
        "name": "Arabic",
        "language_code_3": "arb",
        "alternate_names": [
            "Arab",
            "Arabian",
            "Arbic",
            "Aribic",
            "Arabe",
            "Levantine",
            "Arabish",
            "Arabiic",
            "Lebanese",
            "Syrian",
            "Yemeni",
            "3arabi",
            "Msarabic",
            "Moroccan",
            "Arabizi",
            "Tunisian",
            "Algerian",
            "3rabi",
        ],
        "countries_associated": [
            "AE",
            "CY",
            "DZ",
            "BH",
            "DJ",
            "EG",
            "IL",
            "IQ",
            "JO",
            "KW",
            "LB",
            "LY",
            "MA",
            "ML",
            "OM",
            "PS",
            "SA",
            "SO",
            "SD",
            "SS",
            "SY",
            "TD",
            "TN",
            "YE",
        ],
        "subreddits": ["r/learn_arabic", "r/arabic", "r/arabs", "r/learnarabic"],
        "thanks": "ﺷﻜﺮﺍﹰ",
    },
    "arc": {
        "alternate_names": None,
        "name": "Aramaic",
        "supported": True,
        "language_code_3": "arc",
        "subreddits": ["r/aramaic"],
        "thanks": "Yishar",
    },
    "arq": {
        "supported": True,
        "name": "Algerian Arabic",
        "language_code_3": "arq",
        "alternate_names": ["Algerian"],
    },
    "art": {
        "language_code_3": "art",
        "name": "Conlang",
        "supported": True,
        "alternate_names": ["Artificial", "Conlang", "Constructed", "Tengwar"],
        "thanks": "There is no word for 'thank you' in Dothraki",
    },
    "ary": {
        "supported": True,
        "name": "Moroccan Arabic",
        "language_code_3": "ary",
        "alternate_names": ["Maghrebi Arabic", "Maghribi"],
        "thanks": " شكرا بزاف",
    },
    "arz": {
        "supported": True,
        "name": "Egyptian Arabic",
        "language_code_3": "arz",
        "alternate_names": ["Massry", "Masri"],
        "thanks": "متشكّرين",
    },
    "as": {
        "supported": False,
        "name": "Assamese",
        "language_code_3": "asm",
        "alternate_names": ["Asamiya", "Asambe", "Asami"],
        "thanks": "ধন্যবাদ",
    },
    "ase": {
        "supported": True,
        "name": "American Sign Language",
        "language_code_3": "ase",
        "alternate_names": ["Asl", "American Signed English", "Ameslan"],
    },
    "av": {
        "supported": False,
        "name": "Avar",
        "language_code_3": "ava",
        "alternate_names": ["Avaro", "Avaric"],
        "thanks": " Баркала",
    },
    "ay": {
        "supported": False,
        "name": "Aymara",
        "language_code_3": "ayr",
        "alternate_names": None,
        "countries_associated": ["PE", "CL", "BO"],
        "thanks": "Juspajaraña",
    },
    "az": {
        "supported": True,
        "name": "Azerbaijani",
        "language_code_3": "azj",
        "alternate_names": ["Azeri"],
        "thanks": "Təşəkkür edirəm",
    },
    "ba": {
        "supported": False,
        "name": "Bashkir",
        "language_code_3": "bak",
        "alternate_names": None,
        "thanks": "рәхмәт",
    },
    "ban": {
        "supported": True,
        "name": "Balinese",
        "language_code_3": "ban",
        "alternate_names": ["Bali"],
        "thanks": "Suksma",
    },
    "be": {
        "supported": True,
        "name": "Belarusian",
        "language_code_3": "bel",
        "alternate_names": [
            "Belarussian",
            "Belorusian",
            "Belorussian",
            "Bielorussian",
            "Byelorussian",
        ],
        "countries_default": "BY",
        "subreddits": ["r/belarusian"],
        "thanks": "Дзякуй",
    },
    "bg": {
        "supported": True,
        "name": "Bulgarian",
        "language_code_3": "bul",
        "alternate_names": None,
        "thanks": "благодаря",
    },
    "bh": {
        "supported": False,
        "name": "Bihari",
        "language_code_3": "bho",
        "alternate_names": ["Bhojpuri", "Maithili", "Magahi"],
        "thanks": "धन्वाद",
    },
    "bi": {
        "supported": False,
        "name": "Bislama",
        "language_code_3": "bis",
        "alternate_names": ["Bichelamar"],
        "thanks": "Tangkyu",
    },
    "bm": {
        "supported": False,
        "name": "Bambara",
        "language_code_3": "bam",
        "alternate_names": None,
        "thanks": "I ni ce",
    },
    "bn": {
        "supported": True,
        "name": "Bengali",
        "language_code_3": "ben",
        "alternate_names": ["Bangala", "Bangla"],
        "countries_default": "BD",
        "subreddits": ["r/bengalilanguage"],
        "thanks": "ধন্যবাদ",
    },
    "bo": {
        "supported": True,
        "name": "Tibetan",
        "language_code_3": "bod",
        "language_code_2b": "tib",
        "alternate_names": ["Tibetic"],
        "subreddits": ["r/tibet", "r/tibetanlanguage"],
        "thanks": "ཐུགས་རྗེ་ཆེ་།",
    },
    "br": {
        "supported": True,
        "name": "Breton",
        "language_code_3": "bre",
        "alternate_names": ["Brezhoneg", "Berton"],
        "subreddits": ["r/breton"],
        "thanks": "Trugarez",
    },
    "bs": {
        "supported": True,
        "name": "Bosnian",
        "language_code_3": "bos",
        "alternate_names": ["Bosnien"],
        "countries_default": "BA",
        "thanks": "Hvala",
    },
    "ca": {
        "supported": True,
        "name": "Catalan",
        "language_code_3": "cat",
        "alternate_names": ["Catalonian", "Valencian", "Catalán"],
        "countries_default": "ES",
        "subreddits": ["r/catalan"],
        "thanks": "Gràcies",
    },
    "ce": {
        "supported": False,
        "name": "Chechen",
        "language_code_3": "che",
        "alternate_names": None,
        "subreddits": ["r/chechnya"],
        "thanks": "Баркалла",
    },
    "ceb": {
        "supported": True,
        "name": "Cebuano",
        "language_code_3": "ceb",
        "alternate_names": ["Cebu", "Visaya", "Bisaya", "Visayan"],
        "thanks": "Salamat",
    },
    "ch": {
        "supported": False,
        "name": "Chamorro",
        "language_code_3": "cha",
        "alternate_names": None,
        "thanks": "Si yu'os ma'åse'",
    },
    "chr": {
        "supported": True,
        "name": "Cherokee",
        "language_code_3": "chr",
        "alternate_names": ["Tsalagi", "ᏣᎳᎩ"],
        "thanks": "ᏩᏙ",
    },
    "co": {
        "supported": True,
        "name": "Corsican",
        "language_code_3": "cos",
        "alternate_names": ["Corsu", "Corso", "Corse"],
        "thanks": "À ringraziavvi",
    },
    "cop": {
        "supported": True,
        "name": "Coptic",
        "language_code_3": "cop",
        "alternate_names": None,
        "thanks": "Sephmot",
    },
    "cr": {
        "supported": False,
        "name": "Cree",
        "language_code_3": "crk",
        "alternate_names": None,
        "thanks": "ᐊᕀᐦᐊᕀ",
    },
    "cs": {
        "supported": True,
        "name": "Czech",
        "language_code_3": "ces",
        "language_code_2b": "cze",
        "alternate_names": ["Bohemian", "Čeština", "Czechoslovakian"],
        "countries_default": "CZ",
        "mistake_abbreviation": "cz",
        "subreddits": ["r/learnczech"],
        "thanks": "Dík",
    },
    "cu": {
        "supported": True,
        "name": "Old Church Slavonic",
        "language_code_3": "chu",
        "alternate_names": [
            "Slavonic",
            "Church Slavonic",
            "Old Slavic",
            "Church Slavic",
        ],
    },
    "cv": {
        "supported": False,
        "name": "Chuvash",
        "language_code_3": "chv",
        "alternate_names": ["Bulgar"],
        "thanks": "Тав",
    },
    "cy": {
        "supported": True,
        "name": "Welsh",
        "language_code_3": "cym",
        "language_code_2b": "wel",
        "alternate_names": ["Wales", "Cymraeg", "Gymraeg"],
        "subreddits": ["r/learnwelsh", "r/cymru", "r/wales"],
        "thanks": "Diolch",
    },
    "da": {
        "supported": True,
        "name": "Danish",
        "language_code_3": "dan",
        "alternate_names": ["Dansk", "Denmark", "Rigsdansk"],
        "countries_default": "DK",
        "mistake_abbreviation": "dk",
        "subreddits": ["r/danishlanguage"],
        "thanks": "Tak",
    },
    "de": {
        "supported": True,
        "name": "German",
        "language_code_3": "deu",
        "language_code_2b": "ger",
        "alternate_names": [
            "Deutsch",
            "Deutsche",
            "Ger",
            "Deutch",
            "Kurrent",
            "Austrian",
            "Sütterlin",
            "Plattdeutsch",
            "Suetterlin",
            "Tedesco",
        ],
        "countries_associated": ["AT", "BE", "CH"],
        "subreddits": ["r/german", "r/de", "r/germany"],
        "thanks": "Danke",
    },
    "dv": {
        "supported": False,
        "name": "Dhivehi",
        "language_code_3": "div",
        "alternate_names": ["Divehi", "Maldivian", "Divehli"],
        "thanks": "ޝުކުރިއްޔާ",
    },
    "dz": {
        "supported": True,
        "name": "Dzongkha",
        "language_code_3": "dzo",
        "alternate_names": ["Bhutanese", "Zongkhar"],
        "thanks": "བཀའ་དྲིན་ཆེ་ལགས།",
    },
    "ee": {
        "supported": False,
        "name": "Ewe",
        "language_code_3": "ewe",
        "alternate_names": None,
        "thanks": "Akpe",
    },
    "egy": {
        "alternate_names": [
            "Hieroglyphs",
            "Hieroglyphic",
            "Hieroglyphics",
            "Hyroglifics",
            "Egyptian Hieroglyphs",
            "Egyptian Hieroglyph",
        ],
        "name": "Ancient Egyptian",
        "supported": True,
        "language_code_3": "egy",
        "subreddits": ["r/ancientegypt"],
        "thanks": "Dua",
    },
    "el": {
        "supported": True,
        "name": "Greek",
        "language_code_3": "ell",
        "language_code_2b": "gre",
        "alternate_names": ["Hellenic", "Greece", "Hellas", "Cypriot", "Modern Greek"],
        "countries_default": "GR",
        "countries_associated": ["CY"],
        "mistake_abbreviation": "gr",
        "subreddits": ["r/greek"],
        "thanks": "Ευχαριστώ",
    },
    "en": {
        "supported": False,
        "name": "English",
        "language_code_3": "eng",
        "alternate_names": [
            "Ingles",
            "Inggeris",
            "Englisch",
            "Inglese",
            "Inglesa",
            "Engrish",
            "Enlighs",
            "Engilsh",
            "Enlish",
            "Englishe",
            "Engish",
            "Engelish",
            "Engliah",
            "Englisg",
            "Englsih",
            "Englkish",
            "Engilish",
            "Enlglish",
            "Englsh",
            "Enghlish",
            "Engligh",
            "Englist",
            "Engkish",
            "Ensglish",
            "Enhlish",
            "Английский",
            "Inggris",
            "Englische",
            "英語",
            "영어",
            "Anglais",
            "Engels",
            "Engelsk",
            "İngilizce",
            "英文",
        ],
        "subreddits": ["r/englishlearning"],
    },
    "eo": {
        "supported": True,
        "name": "Esperanto",
        "language_code_3": "epo",
        "alternate_names": None,
        "subreddits": ["r/esperanto"],
        "thanks": "Dankon",
    },
    "es": {
        "supported": True,
        "name": "Spanish",
        "language_code_3": "spa",
        "alternate_names": [
            "Espanol",
            "Spainish",
            "Mexican",
            "Castilian",
            "Español",
            "Spain",
            "Esp",
            "Chilean",
            "Castellano",
            "Españo",
        ],
        "countries_associated": [
            "MX",
            "VE",
            "AR",
            "BO",
            "CL",
            "CO",
            "CR",
            "CU",
            "DO",
            "EC",
            "SV",
            "GQ",
            "GT",
            "HN",
            "NI",
            "PA",
            "PY",
            "PE",
            "PR",
            "UY",
        ],
        "subreddits": ["r/spanish", "r/learnspanish", "r/argentina"],
        "thanks": "Gracias",
    },
    "et": {
        "supported": True,
        "name": "Estonian",
        "language_code_3": "ekk",
        "alternate_names": ["Eesti"],
        "countries_default": "EE",
        "subreddits": ["r/eesti"],
        "thanks": "Tänan",
    },
    "eu": {
        "supported": True,
        "name": "Basque",
        "language_code_3": "eus",
        "language_code_2b": "baq",
        "alternate_names": ["Euska", "EuskeraEuskerie", "Euskara"],
        "countries_default": "ES",
        "subreddits": ["r/basque"],
        "thanks": "Eskerrik asko",
    },
    "fa": {
        "supported": True,
        "name": "Persian",
        "language_code_3": "pes",
        "language_code_2b": "per",
        "alternate_names": ["Farsi", "Iranian", "Iran", "Parsi", "Farse", "Farci"],
        "countries_default": "IR",
        "countries_associated": ["AF"],
        "subreddits": ["r/farsi", "r/iran", "r/learnfarsi", "r/persian"],
        "thanks": "ممنونم",
    },
    "ff": {
        "supported": False,
        "name": "Fula",
        "language_code_3": "fuf",
        "alternate_names": ["Fulah"],
        "countries_associated": [
            "SN",
            "GM",
            "MR",
            "SL",
            "GN",
            "GW",
            "ML",
            "GH",
            "TG",
            "BJ",
            "BF",
            "NE",
            "SD",
            "TD",
            "CM",
            "CF",
            "NG",
        ],
    },
    "fi": {
        "supported": True,
        "name": "Finnish",
        "language_code_3": "fin",
        "alternate_names": ["Finnic", "Suomi", "Finland"],
        "subreddits": ["r/learnfinnish"],
        "thanks": "Kiitos",
    },
    "fj": {
        "supported": False,
        "name": "Fijian",
        "language_code_3": "fij",
        "alternate_names": None,
        "thanks": "Vinaka",
    },
    "fo": {
        "supported": True,
        "name": "Faroese",
        "language_code_3": "fao",
        "alternate_names": ["Faeroese"],
        "subreddits": ["r/faroese"],
        "thanks": "Takk",
    },
    "fr": {
        "supported": True,
        "name": "French",
        "language_code_3": "fra",
        "language_code_2b": "fre",
        "alternate_names": ["Francais", "Français", "Quebecois", "France", "Québécois"],
        "countries_associated": [
            "BE",
            "CA",
            "CF",
            "CD",
            "DJ",
            "GQ",
            "HT",
            "ML",
            "NE",
            "SN",
            "CH",
            "TG",
        ],
        "subreddits": ["r/french", "r/france", "r/frenchimmersion"],
        "thanks": "Merci",
    },
    "fy": {
        "supported": False,
        "name": "Frisian",
        "language_code_3": "fry",
        "alternate_names": None,
        "thanks": "Tankewol",
    },
    "ga": {
        "supported": True,
        "name": "Irish",
        "language_code_3": "gle",
        "alternate_names": ["Gaeilge", "Gaelic"],
        "countries_default": "IE",
        "subreddits": ["r/gaeilge"],
        "thanks": "Go raibh míle maith agat",
    },
    "gd": {
        "supported": True,
        "name": "Scottish Gaelic",
        "language_code_3": "gla",
        "alternate_names": ["Gaidhlig", "Scottish Gaelic", "Scots Gaelic"],
        "subreddits": ["r/gaidhlig"],
        "thanks": "Tapadh leat",
    },
    "generic": {
        "supported": True,
        "name": "Generic",
        "language_code_3": "generic",
        "alternate_names": None,
    },
    "gl": {
        "supported": False,
        "name": "Galician",
        "language_code_3": "glg",
        "alternate_names": ["Gallego", "Galego"],
        "thanks": "Grazas",
    },
    "gn": {
        "supported": False,
        "name": "Guarani",
        "language_code_3": "grn",
        "alternate_names": None,
        "countries_associated": ["PY", "AR", "BO"],
        "thanks": "Aguyje",
    },
    "grc": {
        "supported": True,
        "name": "Ancient Greek",
        "language_code_3": "grc",
        "alternate_names": [
            "Koine",
            "Doric",
            "Attic",
            "Byzantine Greek",
            "Medieval Greek",
            "Classic Greek",
            "Classical Greek",
            "Koine Greek",
            "Greek Koine",
        ],
        "subreddits": ["r/ancientgreek"],
        "thanks": "Ἐπαινῶ",
    },
    "gsw": {
        "supported": True,
        "name": "Swiss German",
        "language_code_3": "gsw",
        "alternate_names": ["Schweizerdeutsch", "Schwyzerdütsch"],
        "thanks": "Merci",
    },
    "gu": {
        "supported": True,
        "name": "Gujarati",
        "language_code_3": "guj",
        "alternate_names": ["Gujerathi", "Gujerati", "Gujrathi"],
        "countries_default": "IN",
        "thanks": "ધન્યવાદ",
    },
    "gv": {
        "supported": False,
        "name": "Manx",
        "language_code_3": "glv",
        "alternate_names": ["Gailck", "Manx Gaelic"],
        "subreddits": ["r/gaelg"],
        "thanks": "Gura mie ayd",
    },
    "ha": {
        "supported": False,
        "name": "Hausa",
        "language_code_3": "hau",
        "alternate_names": ["Haoussa", "Hausawa"],
        "countries_associated": ["NE", "NG", "TD"],
        "thanks": "Na gode",
    },
    "haw": {
        "supported": True,
        "name": "Hawaiian",
        "language_code_3": "haw",
        "alternate_names": ["Hawai'Ian", "Hawaii", "Hawai'I"],
        "subreddits": ["r/learn_hawaiian"],
        "thanks": "Mahalo",
    },
    "he": {
        "supported": True,
        "name": "Hebrew",
        "language_code_3": "heb",
        "alternate_names": ["Israeli", "Hebraic", "Jewish"],
        "countries_default": "IL",
        "subreddits": ["r/hebrew", "r/israel"],
        "thanks": "תודה רבה",
    },
    "hi": {
        "supported": True,
        "name": "Hindi",
        "language_code_3": "hin",
        "alternate_names": ["Hindustani", "Hindī"],
        "countries_default": "IN",
        "countries_associated": ["FJ"],
        "subreddits": ["r/hindi"],
        "thanks": "धन्यवाद",
    },
    "ho": {
        "supported": False,
        "name": "Hiri Motu",
        "language_code_3": "hmo",
        "alternate_names": None,
        "thanks": "Tanikiu",
    },
    "hr": {
        "supported": True,
        "name": "Croatian",
        "language_code_3": "hrv",
        "alternate_names": ["Croation", "Serbo-Croatian", "Hrvatski"],
        "subreddits": ["r/croatian"],
        "thanks": "Hvala",
    },
    "ht": {
        "supported": True,
        "name": "Haitian Creole",
        "language_code_3": "hat",
        "alternate_names": ["Haitian", "Kreyòl Ayisyen", "Kreyol"],
        "subreddits": "r/haiti",
        "thanks": "Mesi",
    },
    "hu": {
        "supported": True,
        "name": "Hungarian",
        "language_code_3": "hun",
        "alternate_names": ["Magyar", "Hungary"],
        "countries_default": "HU",
        "subreddits": ["r/hungarian", "r/hungary"],
        "thanks": "Köszi",
    },
    "hy": {
        "supported": True,
        "name": "Armenian",
        "language_code_3": "hye",
        "language_code_2b": "arm",
        "alternate_names": None,
        "countries_default": "AM",
        "subreddits": ["r/hayeren"],
        "thanks": "մերսի",
    },
    "hz": {
        "supported": False,
        "name": "Herero",
        "language_code_3": "her",
        "alternate_names": None,
        "thanks": "Okuhepa",
    },
    "ia": {
        "supported": False,
        "name": "Interlingua",
        "language_code_3": "ina",
        "alternate_names": None,
        "subreddits": ["r/interlingua"],
        "thanks": "Gratias",
    },
    "id": {
        "supported": True,
        "name": "Indonesian",
        "language_code_3": "ind",
        "alternate_names": ["Indonesia", "Indo"],
        "subreddits": ["r/indonesian"],
        "thanks": "Terima kasih",
    },
    "ie": {
        "supported": False,
        "name": "Interlingue",
        "language_code_3": "ile",
        "alternate_names": None,
        "subreddits": ["r/interlingue"],
        "thanks": "Mersi",
    },
    "ig": {
        "supported": False,
        "name": "Igbo",
        "language_code_3": "ibo",
        "alternate_names": ["Ibo"],
        "thanks": "Ịmela",
    },
    "ii": {
        "supported": False,
        "name": "Nuosu",
        "language_code_3": "iii",
        "alternate_names": None,
        "thanks": "Kax sha w",
    },
    "ik": {
        "supported": False,
        "name": "Inupiaq",
        "language_code_3": "ipk",
        "alternate_names": ["Inupiat", "Iñupiaq"],
        "thanks": "Quyanaq",
    },
    "io": {
        "supported": False,
        "name": "Ido",
        "language_code_3": "ido",
        "alternate_names": None,
        "subreddits": ["r/ido"],
        "thanks": "Danko",
    },
    "is": {
        "supported": True,
        "name": "Icelandic",
        "language_code_3": "isl",
        "language_code_2b": "ice",
        "alternate_names": None,
        "subreddits": ["r/learnicelandic", "r/iceland"],
        "thanks": "Takk",
    },
    "it": {
        "supported": True,
        "name": "Italian",
        "language_code_3": "ita",
        "alternate_names": ["Italiano", "Italiana", "Italia", "Italien", "Italy"],
        "subreddits": ["r/italianlearning", "r/italy"],
        "thanks": "Grazie",
    },
    "iu": {
        "supported": True,
        "name": "Inuktitut",
        "language_code_3": "ike",
        "alternate_names": ["Inuit"],
        "subreddits": ["r/inuktitut"],
        "thanks": "ᖁᔭᓇᐃᓐᓂ",
    },
    "ja": {
        "supported": True,
        "name": "Japanese",
        "language_code_3": "jpn",
        "alternate_names": [
            "Jap",
            "Jpn",
            "Japenese",
            "Japaneese",
            "Japanes",
            "Katakana",
            "Hiragana",
            "Japaness",
            "Romaji",
            "Japneese",
            "Japnese",
            "Kanji",
            "Japaese",
            "Japonais",
            "Romajin",
            "Nihongo",
            "Kenji",
            "Romanji",
            "Rōmaji",
            "日本語",
            "Japones",
            "Japonés",
            "Japnese",
            "Japanase",
            "Japanesse",
        ],
        "countries_default": "JP",
        "mistake_abbreviation": "jp",
        "subreddits": [
            "r/learnjapanese",
            "r/japan",
            "r/japanese",
            "r/nihongo",
            "r/kanji",
            "r/japanlife",
        ],
        "thanks": "ありがとう",
    },
    "jv": {
        "supported": True,
        "name": "Javanese",
        "language_code_3": "jav",
        "alternate_names": ["Djawa"],
        "thanks": "Trim",
    },
    "ka": {
        "supported": True,
        "name": "Georgian",
        "language_code_3": "kat",
        "language_code_2b": "geo",
        "alternate_names": ["Kartvelian"],
        "countries_default": "GE",
        "thanks": "გმადლობთ",
    },
    "kg": {
        "supported": False,
        "name": "Kongo",
        "language_code_3": "kon",
        "alternate_names": ["Kikongo"],
    },
    "ki": {
        "supported": False,
        "name": "Kikuyu",
        "language_code_3": "kik",
        "alternate_names": ["Gikuyu"],
    },
    "kj": {
        "supported": False,
        "name": "Kwanyama",
        "language_code_3": "kua",
        "alternate_names": ["Kuanyama"],
        "thanks": "Tangi",
    },
    "kk": {
        "supported": True,
        "name": "Kazakh",
        "language_code_3": "kaz",
        "alternate_names": ["Kazakhstan", "Kazak", "Kaisak", "Kosach", "Kazakhstani"],
        "countries_default": "KZ",
        "thanks": "Рахмет",
    },
    "kl": {
        "supported": True,
        "name": "Kalaallisut",
        "language_code_3": "kal",
        "alternate_names": ["Greenlandic"],
        "subreddits": ["r/kalaallisut"],
        "thanks": "Qujan",
    },
    "km": {
        "supported": True,
        "name": "Khmer",
        "language_code_3": "khm",
        "alternate_names": ["Cambodian", "Cambodia", "Kampuchea", "Central Khmer"],
        "countries_default": "KH",
        "mistake_abbreviation": "kh",
        "subreddits": ["r/learnkhmer"],
        "thanks": "ឣរគុណ",
    },
    "kn": {
        "supported": True,
        "name": "Kannada",
        "language_code_3": "kan",
        "alternate_names": None,
        "subreddits": ["r/kannada"],
        "thanks": "ಧನ್ಯವಾದಗಳು",
    },
    "ko": {
        "supported": True,
        "name": "Korean",
        "language_code_3": "kor",
        "alternate_names": [
            "Korea",
            "Hangul",
            "Korian",
            "Kor",
            "Hanguk",
            "Guk-Eo",
            "Hangeul",
            "Hanguel",
            "한국어",
        ],
        "countries_default": "KR",
        "subreddits": ["r/korean", "r/korea", "r/koreantranslate"],
        "thanks": "감사합니다",
    },
    "kr": {
        "supported": False,
        "name": "Kanuri",
        "language_code_3": "kau",
        "alternate_names": None,
    },
    "ks": {
        "supported": False,
        "name": "Kashmiri",
        "language_code_3": "kas",
        "alternate_names": ["Kacmiri", "Kaschemiri", "Keshur", "Koshur"],
    },
    "ku": {
        "supported": True,
        "name": "Kurdish",
        "language_code_3": "ckb",
        "alternate_names": ["Kurdi", "Kurd", "Kurmanji"],
        "countries_default": "IQ",
        "thanks": "سوپاس",
    },
    "kv": {
        "supported": False,
        "name": "Komi",
        "language_code_3": "kom",
        "alternate_names": None,
        "thanks": "Аттьӧ",
    },
    "kw": {
        "supported": False,
        "name": "Cornish",
        "language_code_3": "cor",
        "alternate_names": None,
        "subreddits": ["r/kernowek"],
        "thanks": "Meur ras",
    },
    "ky": {
        "supported": False,
        "name": "Kyrgyz",
        "language_code_3": "kir",
        "alternate_names": ["Kirghiz", "Kirgiz"],
        "subreddits": ["r/learnkyrgyz"],
        "thanks": "Рахмат",
    },
    "la": {
        "supported": True,
        "name": "Latin",
        "language_code_3": "lat",
        "alternate_names": ["Latina", "Classical Roman"],
        "subreddits": ["r/latin", "r/mylatintattoo", "r/latina"],
        "thanks": "Grātiās tibi agō",
    },
    "lb": {
        "supported": True,
        "name": "Luxembourgish",
        "language_code_3": "ltz",
        "alternate_names": [
            "Letzeburgesch",
            "Letzburgisch",
            "Luxembourgeois",
            "Luxemburgian",
            "Luxemburgish",
        ],
        "subreddits": ["r/luxembourg"],
        "thanks": "Merci",
    },
    "lg": {
        "supported": False,
        "name": "Ganda",
        "language_code_3": "lug",
        "alternate_names": ["Kiganda", "Luganda"],
        "thanks": "Weebale",
    },
    "li": {
        "supported": True,
        "name": "Limburgish",
        "language_code_3": "lim",
        "alternate_names": [
            "Limburgan",
            "Limburger",
            "Limburgs",
            "Limburgian",
            "Limburgic",
        ],
        "thanks": "Danke",
    },
    "ln": {
        "supported": True,
        "name": "Lingala",
        "language_code_3": "lin",
        "alternate_names": ["Lingála", "Ngala"],
        "thanks": "Botondi",
    },
    "lo": {
        "supported": True,
        "name": "Lao",
        "language_code_3": "lao",
        "alternate_names": ["Laos", "Laotian"],
        "subreddits": ["r/laos"],
        "thanks": "ຂອບໃຈ",
    },
    "lt": {
        "supported": True,
        "name": "Lithuanian",
        "language_code_3": "lit",
        "alternate_names": [
            "Lithuania",
            "Lietuviu",
            "Litauische",
            "Litewski",
            "Litovskiy",
            "Lith",
        ],
        "thanks": "Ačiū",
    },
    "lu": {
        "supported": False,
        "name": "Luba-Kasai",
        "language_code_3": "lub",
        "alternate_names": ["Luba-Katanga", "Cilubà", "Tshilubà"],
    },
    "lv": {
        "supported": True,
        "name": "Latvian",
        "language_code_3": "lvs",
        "alternate_names": None,
        "subreddits": ["r/learnlatvian"],
        "thanks": "Paldies",
    },
    "lzh": {
        "alternate_names": [
            "Literary Chinese",
            "Literary Sinitic",
            "Classical Sinitic",
            "文言文",
            "古文",
        ],
        "name": "Classical Chinese",
        "supported": True,
        "language_code_3": "lzh",
        "subreddits": ["r/classicalchinese"],
        "thanks": "謝",
    },
    "mg": {
        "supported": True,
        "name": "Malagasy",
        "language_code_3": "mlg",
        "alternate_names": ["Madagascar"],
        "subreddits": ["r/madagascar"],
        "thanks": "Misaotra",
    },
    "mh": {
        "supported": False,
        "name": "Marshallese",
        "language_code_3": "mah",
        "alternate_names": None,
    },
    "mi": {
        "supported": True,
        "name": "Maori",
        "language_code_3": "mri",
        "language_code_2b": "mao",
        "alternate_names": ["Māori"],
        "subreddits": ["r/maori"],
        "thanks": "Kia ora",
    },
    "mk": {
        "supported": True,
        "name": "Macedonian",
        "language_code_3": "mkd",
        "language_code_2b": "mac",
        "alternate_names": ["Macedonia"],
        "thanks": "Благодарам",
    },
    "ml": {
        "supported": True,
        "name": "Malayalam",
        "language_code_3": "mal",
        "alternate_names": None,
        "subreddits": ["r/malayalam"],
        "thanks": "നന്ദി",
    },
    "mn": {
        "supported": True,
        "name": "Mongolian",
        "language_code_3": "khk",
        "alternate_names": None,
        "subreddits": ["r/mongolian"],
        "thanks": "Баярлалаа",
    },
    "mr": {
        "supported": True,
        "name": "Marathi",
        "language_code_3": "mar",
        "alternate_names": None,
        "countries_default": "IN",
        "subreddits": ["r/marathi"],
        "thanks": "आभारी आहे",
    },
    "ms": {
        "supported": True,
        "name": "Malay",
        "language_code_3": "zlm",
        "language_code_2b": "may",
        "alternate_names": ["Malaysia", "Melayu", "Malaysian"],
        "countries_default": "MY",
        "countries_associated": ["BN", "SG"],
        "subreddits": ["r/bahasamelayu"],
        "thanks": "Terima kasih",
    },
    "mt": {
        "supported": True,
        "name": "Maltese",
        "language_code_3": "mlt",
        "alternate_names": ["Malti"],
        "thanks": "Grazzi",
    },
    "multiple": {
        "language_code_3": "multiple",
        "alternate_names": [
            "Various",
            "Any",
            "All",
            "Multi",
            "Multi-language",
            "Many",
            "Everything",
            "Anything",
            "Every Language",
            "Mul",
        ],
        "name": "Multiple Languages",
        "supported": True,
    },
    "my": {
        "supported": True,
        "name": "Burmese",
        "language_code_3": "mya",
        "language_code_2b": "bur",
        "alternate_names": ["Myanmar", "Birmanie"],
        "countries_default": "MM",
        "subreddits": ["r/lanl_burmese"],
        "thanks": "ကျေးဇူးတင်ပါတယ်",
    },
    "na": {
        "supported": False,
        "name": "Nauruan",
        "language_code_3": "nau",
        "alternate_names": ["Nauru"],
        "thanks": "Itûba",
    },
    "nap": {
        "supported": True,
        "name": "Neapolitan",
        "language_code_3": "nap",
        "alternate_names": ["Napulitano", "Napolitano"],
    },
    "nb": {
        "supported": False,
        "name": "Norwegian Bokmal",
        "language_code_3": "nob",
        "alternate_names": None,
        "thanks": "Takk",
    },
    "nd": {
        "supported": False,
        "name": "Northern Ndebele",
        "language_code_3": "nde",
        "alternate_names": ["North Ndebele"],
        "thanks": "Ngiyabonga",
    },
    "ne": {
        "supported": True,
        "name": "Nepali",
        "language_code_3": "npi",
        "alternate_names": ["Nepalese", "Nepal"],
        "thanks": "धन्यवाद",
    },
    "ng": {
        "supported": False,
        "name": "Ndonga",
        "language_code_3": "ndo",
        "alternate_names": None,
    },
    "nl": {
        "supported": True,
        "name": "Dutch",
        "language_code_3": "nld",
        "language_code_2b": "dut",
        "alternate_names": ["Nederlands", "Holland", "Netherlands", "Flemish"],
        "countries_associated": ["BE", "SR"],
        "subreddits": ["r/learndutch"],
        "thanks": "Dank u",
    },
    "nn": {
        "supported": False,
        "name": "Norwegian Nynorsk",
        "language_code_3": "nno",
        "alternate_names": None,
        "thanks": "Takk",
    },
    "no": {
        "supported": True,
        "name": "Norwegian",
        "language_code_3": "nor",
        "alternate_names": ["Bokmal", "Norsk", "Nynorsk", "Norway", "Norweigian"],
        "subreddits": ["r/norsk", "r/norway"],
        "thanks": "Takk",
    },
    "non": {
        "alternate_names": ["Nordic", "Futhark", "Viking"],
        "name": "Norse",
        "supported": True,
        "language_code_3": "non",
        "thanks": "Þakka",
    },
    "nr": {
        "supported": False,
        "name": "Southern Ndebele",
        "language_code_3": "nbl",
        "alternate_names": ["Isindebele", "South Ndebele"],
        "thanks": "Ngiyabonga",
    },
    "nv": {
        "supported": True,
        "name": "Navajo",
        "language_code_3": "nav",
        "alternate_names": ["Navaho", "Diné", "Naabeehó"],
        "thanks": "Ahéhee'",
    },
    "ny": {
        "supported": False,
        "name": "Chichewa",
        "language_code_3": "nya",
        "alternate_names": ["Chewa", "Nyanja"],
        "thanks": "Zikomo",
    },
    "oc": {
        "supported": False,
        "name": "Occitan",
        "language_code_3": "oci",
        "alternate_names": None,
        "subreddits": ["r/occitan"],
        "thanks": "Mercés",
    },
    "oj": {
        "supported": False,
        "name": "Ojibwe",
        "language_code_3": "oji",
        "alternate_names": ["Ojibwa"],
        "thanks": "Miigwech",
    },
    "om": {
        "supported": True,
        "name": "Oromo",
        "language_code_3": "orm",
        "alternate_names": ["Oromoo", "Oromiffa", "Oromifa", "Oromos"],
        "countries_associated": ["ET", "KE"],
        "thanks": "Galatoomi",
    },
    "or": {
        "supported": False,
        "name": "Oriya",
        "language_code_3": "ori",
        "alternate_names": ["Odia"],
        "thanks": "ଧନ୍ୟବାଦ୍",
    },
    "os": {
        "supported": False,
        "name": "Ossetian",
        "language_code_3": "oss",
        "alternate_names": ["Ossetic"],
        "thanks": "Бузныг",
    },
    "ota": {
        "alternate_names": ["Ottoman"],
        "name": "Ottoman Turkish",
        "supported": True,
        "language_code_3": "ota",
    },
    "pa": {
        "supported": True,
        "name": "Punjabi",
        "language_code_3": "pan",
        "alternate_names": ["Panjabi", "Punjab", "Panjab"],
        "countries_default": "PK",
        "subreddits": ["r/punjabi"],
        "thanks": "ਧਨਵਾਦ",
    },
    "pi": {
        "supported": True,
        "name": "Pali",
        "language_code_3": "pli",
        "alternate_names": ["Pāli"],
        "subreddits": ["r/pali"],
    },
    "pl": {
        "supported": True,
        "name": "Polish",
        "language_code_3": "pol",
        "alternate_names": ["Polnish", "Polnisch", "Poland", "Polisch", "Polski"],
        "subreddits": ["r/learnpolish", "r/poland"],
        "thanks": "Dzięki",
    },
    "ps": {
        "supported": True,
        "name": "Pashto",
        "language_code_3": "pst",
        "alternate_names": ["Pashtun", "Pushto", "Poshtu"],
        "countries_default": "AF",
        "subreddits": ["r/pashto"],
        "thanks": "مننه",
    },
    "pt": {
        "supported": True,
        "name": "Portuguese",
        "language_code_3": "por",
        "alternate_names": [
            "Portugese",
            "Portugues",
            "Brazilian",
            "Portugais",
            "Brazil",
            "Brazilians",
            "Portugal",
            "Português",
        ],
        "countries_associated": ["AO", "BR", "MZ", "TL", "CV"],
        "subreddits": ["r/portuguese", "r/portugal", "r/brazil"],
        "thanks": "Obrigado",
    },
    "qu": {
        "supported": True,
        "name": "Quechua",
        "language_code_3": "que",
        "alternate_names": ["Kichwa"],
        "subreddits": ["r/learnquechua"],
        "thanks": "Solpayki",
    },
    "rm": {
        "supported": False,
        "name": "Romansh",
        "language_code_3": "roh",
        "alternate_names": None,
        "thanks": "Grazia",
    },
    "rn": {
        "supported": False,
        "name": "Kirundi",
        "language_code_3": "run",
        "alternate_names": ["Ikirundi", "Rundi", "Urundi", "Hima"],
        "thanks": "Urakoze",
    },
    "ro": {
        "supported": True,
        "name": "Romanian",
        "language_code_3": "ron",
        "language_code_2b": "rum",
        "alternate_names": None,
        "countries_associated": ["MD"],
        "subreddits": ["r/romanian"],
        "thanks": "Mersi",
    },
    "ru": {
        "supported": True,
        "name": "Russian",
        "language_code_3": "rus",
        "alternate_names": [
            "Russain",
            "Russin",
            "Russion",
            "Rus",
            "Rusian",
            "Ruski",
            "ру́сский",
            "Русский",
        ],
        "subreddits": ["r/russian", "r/russia"],
        "thanks": "Спаси́бо",
    },
    "rw": {
        "supported": False,
        "name": "Kinyarwanda",
        "language_code_3": "kin",
        "alternate_names": [
            "Ikinyarwanda",
            "Orunyarwanda",
            "Ruanda",
            "Rwanda",
            "Rwandan",
            "Urunyaruanda",
        ],
        "thanks": "Murakoze",
    },
    "sa": {
        "supported": True,
        "name": "Sanskrit",
        "language_code_3": "san",
        "alternate_names": ["Samskrit", "Sandskrit"],
        "subreddits": ["r/sanskrit"],
        "thanks": "धन्यवादाः",
    },
    "sc": {
        "supported": True,
        "name": "Sardinian",
        "language_code_3": "sro",
        "alternate_names": ["Sardu"],
        "thanks": "Grazie",
    },
    "scn": {
        "supported": True,
        "name": "Sicilian",
        "language_code_3": "scn",
        "alternate_names": ["Siciliano", "Sicilianu", "Siculu"],
        "thanks": "Grazij",
    },
    "sd": {
        "supported": False,
        "name": "Sindhi",
        "language_code_3": "snd",
        "alternate_names": None,
        "thanks": "Mehrbani",
    },
    "se": {
        "supported": False,
        "name": "Northern Sami",
        "language_code_3": "sme",
        "alternate_names": None,
        "thanks": "Giitu",
    },
    "sg": {
        "supported": False,
        "name": "Sango",
        "language_code_3": "sag",
        "alternate_names": None,
        "thanks": "Singîla",
    },
    "si": {
        "supported": True,
        "name": "Sinhalese",
        "language_code_3": "sin",
        "alternate_names": ["Sinhala", "Sri Lanka", "Sri Lankan"],
        "countries_default": "LK",
        "subreddits": ["r/sinhala"],
        "thanks": "Istuti",
    },
    "sk": {
        "supported": True,
        "name": "Slovak",
        "language_code_3": "slk",
        "language_code_2b": "slo",
        "alternate_names": ["Slovakian", "Slovakia"],
        "thanks": "Ďakujem",
    },
    "sl": {
        "supported": True,
        "name": "Slovene",
        "language_code_3": "slv",
        "alternate_names": ["Slovenian", "Slovenski"],
        "countries_default": "SI",
        "thanks": "Hvala",
    },
    "sm": {
        "supported": False,
        "name": "Samoan",
        "language_code_3": "smo",
        "alternate_names": None,
        "thanks": "Fa'afetai",
    },
    "sn": {
        "supported": False,
        "name": "Shona",
        "language_code_3": "sna",
        "alternate_names": None,
        "thanks": "Waita zvako",
    },
    "so": {
        "supported": True,
        "name": "Somali",
        "language_code_3": "som",
        "alternate_names": ["Somalia", "Somalian"],
        "thanks": "Mahadsanid",
    },
    "sq": {
        "supported": True,
        "name": "Albanian",
        "language_code_3": "als",
        "language_code_2b": "alb",
        "alternate_names": ["Shqip", "Shqipe", "Tosk"],
        "countries_default": "AL",
        "countries_associated": ["XK"],
        "subreddits": ["r/albanian"],
        "thanks": "Falemenderit",
    },
    "sr": {
        "supported": True,
        "name": "Serbian",
        "language_code_3": "srp",
        "alternate_names": ["Yugoslavian"],
        "countries_default": "RS",
        "countries_associated": ["ME"],
        "subreddits": ["r/serbian"],
        "thanks": "Хвала",
    },
    "ss": {
        "supported": False,
        "name": "Swati",
        "language_code_3": "ssw",
        "alternate_names": ["Swazi"],
        "thanks": "Ngiyabonga",
    },
    "st": {
        "supported": False,
        "name": "Sotho",
        "language_code_3": "sot",
        "alternate_names": None,
        "thanks": "Ke a leboha",
    },
    "su": {
        "supported": False,
        "name": "Sundanese",
        "language_code_3": "sun",
        "alternate_names": None,
        "thanks": "Nuhun",
    },
    "sv": {
        "supported": True,
        "name": "Swedish",
        "language_code_3": "swe",
        "alternate_names": [
            "Svenska",
            "Swede",
            "Sweedish",
            "Swedisch",
            "Swidish",
            "Gutnish",
            "Sweden",
        ],
        "countries_default": "SE",
        "subreddits": ["r/svenska", "r/sweden"],
        "thanks": "Tack",
    },
    "sw": {
        "supported": True,
        "name": "Swahili",
        "language_code_3": "swh",
        "alternate_names": ["Kiswahili", "Suaheli"],
        "countries_associated": ["CD", "TZ", "KE", "UG"],
        "subreddits": ["r/swahili"],
        "thanks": "Asante",
    },
    "syc": {
        "alternate_names": ["Classical Syriac"],
        "name": "Syriac",
        "supported": True,
        "language_code_3": "syc",
    },
    "ta": {
        "supported": True,
        "name": "Tamil",
        "language_code_3": "tam",
        "alternate_names": None,
        "countries_default": "IN",
        "countries_associated": ["SG"],
        "subreddits": ["r/tamil"],
        "thanks": "நன்றி",
    },
    "te": {
        "supported": True,
        "name": "Telugu",
        "language_code_3": "tel",
        "alternate_names": ["Tegulu"],
        "countries_default": "IN",
        "subreddits": ["r/telugu"],
        "thanks": "ధన్యవాదములు",
    },
    "tg": {
        "supported": True,
        "name": "Tajik",
        "language_code_3": "tgk",
        "alternate_names": None,
        "mistake_abbreviation": "tj",
        "thanks": "Рахмат",
    },
    "th": {
        "supported": True,
        "name": "Thai",
        "language_code_3": "tha",
        "alternate_names": ["Thailand", "Siamese", "Bangkok", "Thi", "Thia"],
        "subreddits": ["r/learnthai", "r/thailand"],
        "thanks": "ขอบคุณ",
    },
    "ti": {
        "supported": False,
        "name": "Tigrinya",
        "language_code_3": "tir",
        "alternate_names": None,
        "thanks": "የቐንየለይ",
    },
    "tk": {
        "supported": False,
        "name": "Turkmen",
        "language_code_3": "tuk",
        "alternate_names": None,
        "thanks": "Sag boluň",
    },
    "tl": {
        "supported": True,
        "name": "Tagalog",
        "language_code_3": "tgl",
        "alternate_names": [
            "Filipino",
            "Fillipino",
            "Philipino",
            "Philippines",
            "Philippine",
            "Phillipene",
            "Phillipenes",
        ],
        "countries_default": "PH",
        "subreddits": ["r/tagalog"],
        "thanks": "Salamat",
    },
    "tn": {
        "supported": False,
        "name": "Tswana",
        "language_code_3": "tsn",
        "alternate_names": ["Setswana"],
        "thanks": "Ke itumetse",
    },
    "to": {
        "supported": False,
        "name": "Tonga",
        "language_code_3": "ton",
        "alternate_names": ["Tongan"],
        "thanks": "Mālō",
    },
    "tr": {
        "supported": True,
        "name": "Turkish",
        "language_code_3": "tur",
        "alternate_names": ["Turkic", "Turkce", "Turkey", "Türkçe"],
        "countries_associated": ["CY"],
        "subreddits": ["r/turkishlearning", "r/turkey"],
        "thanks": "Teşekkür ederim",
    },
    "ts": {
        "supported": False,
        "name": "Tsonga",
        "language_code_3": "tso",
        "alternate_names": None,
        "thanks": "Ndza nkhensa",
    },
    "tt": {
        "supported": True,
        "name": "Tatar",
        "language_code_3": "tat",
        "alternate_names": None,
        "thanks": "Räxmät",
    },
    "tw": {
        "supported": True,
        "name": "Twi",
        "language_code_3": "twi",
        "alternate_names": None,
        "thanks": "Meda wo ase",
    },
    "ty": {
        "supported": False,
        "name": "Tahitian",
        "language_code_3": "tah",
        "alternate_names": None,
        "thanks": "Māuruuru",
    },
    "ug": {
        "supported": True,
        "name": "Uyghur",
        "language_code_3": "uig",
        "alternate_names": ["Uighur"],
        "thanks": "رەھمەت سىزگە",
    },
    "uk": {
        "supported": True,
        "name": "Ukrainian",
        "language_code_3": "ukr",
        "alternate_names": ["Ukranian", "Ukraine"],
        "countries_default": "UA",
        "mistake_abbreviation": "ua",
        "subreddits": ["r/ukrainian"],
        "thanks": "Дякую",
    },
    "unknown": {
        "language_code_3": "unknown",
        "alternate_names": [
            "Unknown",
            "Unkown",
            "Unknow",
            "Uknown",
            "Unknon",
            "Unsure",
            "Asian",
            "Asiatic",
            "Not Sure",
            "Don'T Know",
            "Dont Know",
            "No Idea",
            "I Don'T Know",
            "Unk",
            "Idk",
            "Undefined",
            "Source Language",
            "Mystery",
            "Native American",
            "Uncertain",
            "Indian",
            "Unidentified",
        ],
        "name": "Unknown",
        "supported": True,
    },
    "ur": {
        "supported": True,
        "name": "Urdu",
        "language_code_3": "urd",
        "alternate_names": ["Pakistani", "Pakistan"],
        "countries_default": "PK",
        "subreddits": ["r/urdu"],
        "thanks": "شكريه",
    },
    "uz": {
        "supported": True,
        "name": "Uzbek",
        "language_code_3": "uzn",
        "alternate_names": None,
        "countries_associated": ["AF"],
        "subreddits": ["r/learn_uzbek"],
        "thanks": "Rahmat",
    },
    "ve": {
        "supported": False,
        "name": "Venda",
        "language_code_3": "ven",
        "alternate_names": None,
        "thanks": "Ndo livhuwa",
    },
    "vi": {
        "supported": True,
        "name": "Vietnamese",
        "language_code_3": "vie",
        "alternate_names": ["Vietnam", "Viet", "Chữ Nôm", "Annamese"],
        "countries_default": "VN",
        "mistake_abbreviation": "vn",
        "subreddits": ["r/vietnamese", "r/vietnam", "r/learnvietnamese"],
        "thanks": "Cảm ơn",
    },
    "vo": {
        "supported": False,
        "name": "Volapuk",
        "language_code_3": "vol",
        "alternate_names": ["Volapük"],
        "subreddits": ["r/volapuk"],
        "thanks": "Danö",
    },
    "wa": {
        "supported": False,
        "name": "Walloon",
        "language_code_3": "wln",
        "alternate_names": None,
        "thanks": "Grâce",
    },
    "wo": {
        "supported": False,
        "name": "Wolof",
        "language_code_3": "wol",
        "alternate_names": None,
        "thanks": "Jai-rruh-jef",
    },
    "xh": {
        "supported": True,
        "name": "Xhosa",
        "language_code_3": "xho",
        "alternate_names": ["Isixhosa"],
        "thanks": "Ndiyabulela",
    },
    "yi": {
        "supported": True,
        "name": "Yiddish",
        "language_code_3": "ydd",
        "alternate_names": ["Yidish"],
        "subreddits": ["r/yiddish"],
        "thanks": "שכח",
    },
    "yo": {
        "supported": True,
        "name": "Yoruba",
        "language_code_3": "yor",
        "alternate_names": None,
        "thanks": "O se",
    },
    "yue": {
        "alternate_names": [
            "Cantonese Chinese",
            "Chinese Cantonese",
            "Canto",
            "Taishanese",
            "Guangzhou",
        ],
        "name": "Cantonese",
        "supported": True,
        "language_code_3": "yue",
        "countries_default": "HK",
        "countries_associated": ["MO"],
        "subreddits": ["r/cantonese"],
        "thanks": "多謝",
    },
    "za": {
        "supported": False,
        "name": "Zhuang",
        "language_code_3": "zyb",
        "alternate_names": None,
    },
    "zh": {
        "supported": True,
        "name": "Chinese",
        "language_code_3": "cmn",
        "language_code_2b": "chi",
        "alternate_names": [
            "Mandarin",
            "Taiwanese",
            "Chinease",
            "Manderin",
            "Zhongwen",
            "中文",
            "汉语",
            "漢語",
            "國語",
            "Chinise",
            "Chineese",
            "Hanzi",
            "Cinese",
            "Mandrin",
            "Mandarin Chinese",
            "Mandirin",
            "Taiwan",
            "China",
            "Chn",
            "Pinyin",
            "Beijinghua",
            "Zhongguohua",
            "Putonghua",
            "Guanhua",
            "Bronze Script",
            "Seal Script",
            "Mandaring",
        ],
        "countries_default": "CN",
        "countries_associated": ["TW"],
        "mistake_abbreviation": "cn",
        "subreddits": [
            "r/chineselanguage",
            "r/chinese",
            "r/mandarin",
            "r/learnchinese",
        ],
        "thanks": "謝謝",
    },
    "zu": {
        "supported": True,
        "name": "Zulu",
        "language_code_3": "zul",
        "alternate_names": ["Isizulu", "Isi Zulu"],
        "countries_default": "ZA",
        "thanks": "Ngiyabonga",
    },
    "zxx": {
        "alternate_names": [
            "Null",
            "None",
            "Nothing",
            "Gibberish",
            "Nonsense",
            "Mojibake",
            "Drunk",
        ],
        "name": "Nonlanguage",
        "supported": True,
        "language_code_3": "zxx",
    },
}

APP_WORDS = [
    " app ",
    " bot ",
    "add-on",
    "addon",
    "an app",
    "android",
    "chatbot",
    "crowdin",
    "crowdsourced",
    "discord bot",
    "firefox",
    "game",
    "google play",
    "localisation",
    "localise",
    "localization",
    "localize",
    "my app",
    "social network",
    "software",
    "telegram bot",
]

# These are English words that usually get erroneously recognized as a language due to Fuzzywuzzy. Let's ignore them.
FUZZ_IGNORE_WORDS = [
    "Ancient Mayan",
    "Archaic",
    "Base",
    "Canada",
    "Cheese",
    "Chopstick",
    "Classical Japanese",
    "Creek",
    "Dish",
    "Green",
    "Guarani",
    "Here",
    "Horse",
    "Japanese",
    "Javanese",
    "Japanese -",
    "Kanada",
    "Karen",
    "Latina",
    "Ladin",
    "Ladino",
    "Latino",
    "Lmao",
    "Logo",
    "Maay",
    "Major",
    "Malaysia",
    "Mardi",
    "Maria",
    "Mario",
    "Morse",
    "Nosey",
    "Nurse",
    "Orkish",
    "Past",
    "Person",
    "Peruvian",
    "Prussian",
    "Roman",
    "Romani",
    "Romanization",
    "Romanized",
    "Romanji",
    "Romanjin",
    "Romany",
    "Sake",
    "Scandinavian",
    "Serial",
    "Sorbian",
    "Sumerian",
    "Syrian Arabic",
    "Titan",
    "Trail",
    "Trench",
    "Turks",
]

# A manually populated dictionary that matches ISO macrolanguages with their most prominent consituent language.
ISO_MACROLANGUAGES = {
    "aka": ("twi", ["fat", "twi"]),
    "ara": (
        "arb",
        [
            "aao",
            "abh",
            "abv",
            "acm",
            "acq",
            "acw",
            "acx",
            "acy",
            "adf",
            "aeb",
            "aec",
            "afb",
            "apc",
            "apd",
            "arb",
            "arq",
            "ars",
            "ary",
            "arz",
            "auz",
            "avl",
            "ayh",
            "ayl",
            "ayn",
            "ayp",
            "bbz",
            "pga",
            "shu",
            "ssh",
        ],
    ),
    "aym": ("ayr", ["ayr", "ayc"]),
    "aze": ("azj", ["azj", "azb"]),
    "bal": ("bgp", ["bcc", "bgn", "bgp"]),
    "bik": ("bcl", ["bcl", "bhk", "bln", "bto", "cts", "fbl", "lbl", "rbl", "ubl"]),
    "bnc": ("lbk", ["ebk", "lbk", "obk", "rbk", "vbk"]),
    "bua": ("bxr", ["bxm", "bxr", "bxu"]),
    "chm": ("mhr", ["mhr", "mrj"]),
    "cre": ("crk", ["crj", "crk", "crl", "crm", "csw", "cwd"]),
    "del": ("umu", ["umu", "unm"]),
    "den": ("xsl", ["scs", "xsl"]),
    "din": ("dik", ["dib", "dik", "dip", "diw", "dks"]),
    "doi": ("dgo", ["dgo", "xnr"]),
    "est": ("ekk", ["ekk", "vro"]),
    "fas": ("pes", ["prs", "pes"]),
    "ful": ("fuf", ["ffm", "fub", "fuc", "fue", "fuf", "fuh", "fui", "fuq", "fuv"]),
    "gba": ("gbp", ["bdt", "gbp", "gbq", "gmm", "gso", "gya", "mdo"]),
    "gon": ("ggo", ["esg", "ggo", "gno", "wsg"]),
    "grb": ("grj", ["gbo", "gec", "grj", "grv", "gry"]),
    "grn": ("gug", ["gnw", "gug", "gui", "gun", "nhd"]),
    "hai": ("hdn", ["hax", "hdn"]),
    "hbs": ("hrv", ["bos", "hrv", "srp"]),
    "hmn": (
        "mww",
        [
            "blu",
            "cqd",
            "hea",
            "hma",
            "hmc",
            "hmd",
            "hme",
            "hmg",
            "hmh",
            "hmi",
            "hmj",
            "hml",
            "hmm",
            "hmp",
            "hmq",
            "hms",
            "hmw",
            "hmy",
            "hmz",
            "hnj",
            "hrm",
            "huj",
            "mmr",
            "muq",
            "mww",
            "sfm",
        ],
    ),
    "iku": ("ike", ["ike", "ikt"]),
    "ipk": ("esi", ["esi", "esk"]),
    "jrb": ("aju", ["ajt", "aju", "jye", "yhd", "yud"]),
    "kau": ("knc", ["kby", "knc", "krt"]),
    "kln": ("niq", ["enb", "eyo", "niq", "oki", "pko", "sgc", "spy", "tec", "tuy"]),
    "kok": ("gom", ["gom", "knn"]),
    "kom": ("kpv", ["koi", "kpv"]),
    "kon": ("kng", ["kng", "kwy", "ldi"]),
    "kpe": ("gkp", ["gkp", "xpe"]),
    "kur": ("kmr", ["ckb", "kmr", "sdh"]),
    "lah": ("skr", ["hnd", "hno", "jat", "phr", "pmu", "pnb", "skr", "xhe"]),
    "lav": ("lvs", ["ltg", "lvs"]),
    "luy": (
        "lwg",
        [
            "bxk",
            "ida",
            "lkb",
            "lko",
            "lks",
            "lri",
            "lrm",
            "lsm",
            "lto",
            "lts",
            "lwg",
            "nle",
            "nyd",
            "rag",
        ],
    ),
    "man": ("mnk", ["emk", "mku", "mlq", "mnk", "msc", "mwk", "myq"]),
    "mlg": (
        "plt",
        [
            "bhr",
            "bjq",
            "bmm",
            "bzc",
            "msh",
            "plt",
            "skg",
            "tdx",
            "tkg",
            "txy",
            "xmv",
            "xmw",
        ],
    ),
    "mon": ("khk", ["khk", "mvf"]),
    "msa": (
        "zsm",
        [
            "bjn",
            "btj",
            "bve",
            "bvu",
            "coa",
            "dup",
            "hji",
            "ind",
            "jak",
            "jax",
            "kvb",
            "kvr",
            "kxd",
            "lce",
            "lcf",
            "liw",
            "max",
            "meo",
            "mfa",
            "mfb",
            "min",
            "mly",
            "mqg",
            "msi",
            "mui",
            "orn",
            "ors",
            "pel",
            "pse",
            "tmw",
            "urk",
            "vkk",
            "vkt",
            "xmm",
            "zlm",
            "zmi",
            "zsm",
        ],
    ),
    "mwr": ("rwr", ["dhd", "mtr", "mve", "rwr", "swv", "wry"]),
    "nep": ("npi", ["npi", "dty"]),
    "nor": ("nob", ["nno", "nob"]),
    "oji": ("ojb", ["ciw", "ojb", "ojc", "ojg", "ojs", "ojw", "otw"]),
    "ori": ("ory", ["ory", "spv"]),
    "orm": ("gaz", ["gaz", "gax", "hae", "orc"]),
    "pus": ("pst", ["pbt", "pbu", "pst"]),
    "que": (
        "quh",
        [
            "cqu",
            "qub",
            "qud",
            "quf",
            "qug",
            "quh",
            "quk",
            "qul",
            "qup",
            "qur",
            "qus",
            "quw",
            "qux",
            "quy",
            "quz",
            "qva",
            "qvc",
            "qve",
            "qvh",
            "qvi",
            "qvj",
            "qvl",
            "qvm",
            "qvn",
            "qvo",
            "qvp",
            "qvs",
            "qvw",
            "qvz",
            "qwa",
            "qwc",
            "qwh",
            "qws",
            "qxa",
            "qxc",
            "qxh",
            "qxl",
            "qxn",
            "qxo",
            "qxp",
            "qxr",
            "qxt",
            "qxu",
            "qxw",
        ],
    ),
    "raj": ("mup", ["bgq", "gda", "gju", "hoj", "mup", "wbr"]),
    "rom": ("rmy", ["rmc", "rmf", "rml", "rmn", "rmo", "rmw", "rmy"]),
    "sqi": ("als", ["aae", "aat", "aln", "als"]),
    "srd": ("src", ["sdc", "sdn", "src", "sro"]),
    "swa": ("swh", ["swh", "swc"]),
    "syr": ("cld", ["aii", "cld"]),
    "tmh": ("ttq", ["taq", "thv", "thz", "ttq"]),
    "uzb": ("uzn", ["uzn", "uzs"]),
    "yid": ("ydd", ["ydd", "yih"]),
    "zap": (
        "zai",
        [
            "zaa",
            "zab",
            "zac",
            "zad",
            "zae",
            "zaf",
            "zai",
            "zam",
            "zao",
            "zaq",
            "zar",
            "zas",
            "zat",
            "zav",
            "zaw",
            "zax",
            "zca",
            "zoo",
            "zpa",
            "zpb",
            "zpc",
            "zpd",
            "zpe",
            "zpf",
            "zpg",
            "zph",
            "zpi",
            "zpj",
            "zpk",
            "zpl",
            "zpm",
            "zpn",
            "zpo",
            "zpp",
            "zpq",
            "zpr",
            "zps",
            "zpt",
            "zpu",
            "zpv",
            "zpw",
            "zpx",
            "zpy",
            "zpz",
            "zsr",
            "ztc",
            "zte",
            "ztg",
            "ztl",
            "ztm",
            "ztn",
            "ztp",
            "ztq",
            "zts",
            "ztt",
            "ztu",
            "ztx",
            "zty",
        ],
    ),
    "zha": (
        "zyb",
        [
            "ccx",
            "ccy",
            "zch",
            "zeh",
            "zgb",
            "zgm",
            "zgn",
            "zhd",
            "zhn",
            "zlj",
            "zln",
            "zlq",
            "zqe",
            "zyb",
            "zyg",
            "zyj",
            "zyn",
            "zzj",
        ],
    ),
    "zho": (
        "cmn",
        [
            "cdo",
            "cjy",
            "cmn",
            "cpx",
            "czh",
            "czo",
            "gan",
            "hak",
            "hsn",
            "lzh",
            "mnp",
            "nan",
            "wuu",
            "yue",
        ],
    ),
    "zza": ("kiu", ["diq", "kiu"]),
}
CJK_LANGUAGES = {
    "Chinese": [
        "Chinese",
        "Min Dong Chinese",
        "Classical Chinese",
        "Jinyu Chinese",
        "Mandarin Chinese",
        "Pu-Xian Chinese",
        "Huizhou Chinese",
        "Min Zhong Chinese",
        "Gan Chinese",
        "Hakka Chinese",
        "Xiang Chinese",
        "Min Bei Chinese",
        "Min Nan Chinese",
        "Wu Chinese",
        "Yue Chinese",
        "Cantonese",
        "Late Middle Chinese",
        "Old Chinese",
        "Hani",
        "Hanb",
        "Hans",
        "Hant",
        "Traditional Han",
        "Simplified Han",
        "Han Characters",
        "Unknown",
    ],
    "Japanese": [
        "Japanese",
        "Old Japanese",
        "Northern Amami-Oshima",
        "Southern Amami-Oshima",
        "Kikai",
        "Toku-No-Shima",
        "Kunigami",
        "Oki-No-Erabu",
        "Central Okinawan",
        "Yoron",
        "Miyako",
        "Yaeyama",
        "Yonaguni",
        "Hira",
        "Jpan",
        "Kana",
    ],
    "Korean": ["Korean", "Middle Korean", "Old Korean", "Jejueo", "Hang", "Kore"],
}


# An ISO 3166 list of countries and their equivalent codes and words. Used for determining regional dialects.
class CountryTuple(NamedTuple):
    name: str
    code2: str
    code3: str
    numeric: str
    aliases: Optional[List[str]] = None


countries = [
    ("Afghanistan", "AF", "AFG", "004", ["Afghan", "Afghani"]),
    ("Albania", "AL", "ALB", "008"),
    ("Algeria", "DZ", "DZA", "012", ["Algerian", "Algerien"]),
    ("Andorra", "AD", "AND", "020", ["Andorran"]),
    ("Angola", "AO", "AGO", "024", ["Angolan"]),
    ("Anguilla", "AI", "AIA", "660"),
    ("Antigua and Barbuda", "AG", "ATG", "028"),
    ("Argentina", "AR", "ARG", "032", ["Argentinian", "Argentine"]),
    ("Armenia", "AM", "ARM", "051"),
    ("Aruba", "AW", "ABW", "533"),
    ("Australia", "AU", "AUS", "036", ["Australian", "Straya"]),
    ("Austria", "AT", "AUT", "040", ["Austrian", "Vienna", "Osterreich"]),
    ("Azerbaijan", "AZ", "AZE", "031"),
    ("Bahamas", "BS", "BHS", "044"),
    ("Bahrain", "BH", "BHR", "048", ["Bahrani"]),
    ("Bangladesh", "BD", "BGD", "050"),
    ("Barbados", "BB", "BRB", "052"),
    ("Belarus", "BY", "BLR", "112"),
    ("Belgium", "BE", "BEL", "056", ["Belgian", "Brussels", "Belgien"]),
    ("Belize", "BZ", "BLZ", "084"),
    ("Benin", "BJ", "BEN", "204"),
    ("Bermuda", "BM", "BMU", "060"),
    ("Bhutan", "BT", "BTN", "064"),
    ("Bolivia, Plurinational State of", "BO", "BOL", "068", ["Bolivian"]),
    ("Bosnia and Herzegovina", "BA", "BIH", "070"),
    ("Botswana", "BW", "BWA", "072"),
    ("Brazil", "BR", "BRA", "076", ["Brazilian", "Brasil", "Brazilien", "Brazillian"]),
    ("Brunei", "BN", "BRN", "096", ["Bruneian", "Darussalam"]),
    ("Bulgaria", "BG", "BGR", "100"),
    ("Burkina Faso", "BF", "BFA", "854"),
    ("Burundi", "BI", "BDI", "108"),
    ("Cambodia", "KH", "KHM", "116"),
    ("Cameroon", "CM", "CMR", "120"),
    ("Canada", "CA", "CAN", "124", ["Canadian", "Quebec", "Quebecois"]),
    ("Cabo Verde", "CV", "CPV", "132"),
    ("Cayman Islands", "KY", "CYM", "136"),
    ("Central African Republic", "CF", "CAF", "140"),
    ("Chad", "TD", "TCD", "148"),
    ("Chile", "CL", "CHL", "152", ["Chilean"]),
    ("China", "CN", "CHN", "156", ["Zhongguo"]),
    ("Colombia", "CO", "COL", "170", ["Colombian"]),
    ("Comoros", "KM", "COM", "174"),
    ("Congo", "CG", "COG", "178"),
    ("Congo, Democratic Republic of the", "CD", "COD", "180", ["Congolese"]),
    ("Cook Islands", "CK", "COK", "184"),
    ("Costa Rica", "CR", "CRI", "188", ["Costa Rican"]),
    ("Côte d'Ivoire", "CI", "CIV", "384", ["Ivory Coast"]),
    ("Croatia", "HR", "HRV", "191"),
    ("Cuba", "CU", "CUB", "192", ["Cuban", "Havana"]),
    ("Curaçao", "CW", "CUW", "531"),
    ("Cyprus", "CY", "CYP", "196", ["Cypriot"]),
    ("Czech Republic", "CZ", "CZE", "203", ["Czechia"]),
    ("Denmark", "DK", "DNK", "208"),
    ("Djibouti", "DJ", "DJI", "262"),
    ("Dominica", "DM", "DMA", "212"),
    ("Dominican Republic", "DO", "DOM", "214", ["Dominican"]),
    ("Ecuador", "EC", "ECU", "218", ["Ecuadorian"]),
    ("Egypt", "EG", "EGY", "818", ["Egyptian"]),
    ("El Salvador", "SV", "SLV", "222", ["El Salvadorian"]),
    ("Equatorial Guinea", "GQ", "GNQ", "226"),
    ("Eritrea", "ER", "ERI", "232"),
    ("Estonia", "EE", "EST", "233"),
    ("Ethiopia", "ET", "ETH", "231"),
    ("Faroe Islands", "FO", "FRO", "234"),
    ("Fiji", "FJ", "FJI", "242", ["Fijian"]),
    ("Finland", "FI", "FIN", "246", ["Finnish"]),
    ("France", "FR", "FRA", "250"),
    ("Gabon", "GA", "GAB", "266"),
    ("Gambia", "GM", "GMB", "270"),
    ("Georgia", "GE", "GEO", "268"),
    ("Germany", "DE", "DEU", "276"),
    ("Ghana", "GH", "GHA", "288"),
    ("Greece", "GR", "GRC", "300"),
    ("Greenland", "GL", "GRL", "304"),
    ("Grenada", "GD", "GRD", "308"),
    ("Guadeloupe", "GP", "GLP", "312"),
    ("Guam", "GU", "GUM", "316"),
    ("Guatemala", "GT", "GTM", "320", ["Guatemalan"]),
    ("Guernsey", "GG", "GGY", "831"),
    ("Guinea", "GN", "GIN", "324"),
    ("Guinea-Bissau", "GW", "GNB", "624"),
    ("Guyana", "GY", "GUY", "328", ["Guyanese"]),
    ("Haiti", "HT", "HTI", "332", ["Haitian"]),
    ("Holy See", "VA", "VAT", "336", ["Vatican"]),
    ("Honduras", "HN", "HND", "340", ["Honduran"]),
    ("Hong Kong", "HK", "HKG", "344", ["Honk Kong"]),
    ("Hungary", "HU", "HUN", "348"),
    ("Iceland", "IS", "ISL", "352"),
    ("India", "IN", "IND", "356", ["Indian"]),
    ("Indonesia", "ID", "IDN", "360"),
    ("Iran, Islamic Republic of", "IR", "IRN", "364"),
    ("Iraq", "IQ", "IRQ", "368", ["Iraqi", "Baghdad"]),
    ("Ireland", "IE", "IRL", "372", ["Irish", "Hiberno"]),
    ("Isle of Man", "IM", "IMN", "833"),
    ("Israel", "IL", "ISR", "376", ["Israeli"]),
    ("Italy", "IT", "ITA", "380"),
    ("Jamaica", "JM", "JAM", "388"),
    ("Japan", "JP", "JPN", "392"),
    ("Jordan", "JO", "JOR", "400", ["Jordanian"]),
    ("Kazakhstan", "KZ", "KAZ", "398"),
    ("Kenya", "KE", "KEN", "404", ["Kenyan"]),
    ("Kiribati", "KI", "KIR", "296"),
    ("North Korea", "KP", "PRK", "408", ["North Korean", "Dprk"]),
    ("South Korea", "KR", "KOR", "410", ["South Korean"]),
    ("Kuwait", "KW", "KWT", "414", ["Kuwaiti"]),
    ("Kyrgyzstan", "KG", "KGZ", "417"),
    ("Laos", "LA", "LAO", "418", ["Laotian"]),
    ("Latvia", "LV", "LVA", "428"),
    ("Lebanon", "LB", "LBN", "422", ["Lebanese", "Beirut"]),
    ("Lesotho", "LS", "LSO", "426"),
    ("Liberia", "LR", "LBR", "430"),
    ("Libya", "LY", "LBY", "434", ["Libyan", "Tripoli"]),
    ("Liechtenstein", "LI", "LIE", "438"),
    ("Lithuania", "LT", "LTU", "440"),
    ("Luxembourg", "LU", "LUX", "442"),
    ("Macao", "MO", "MAC", "446", ["Macau", "Aomen"]),
    ("Macedonia, the former Yugoslav Republic of", "MK", "MKD", "807"),
    ("Madagascar", "MG", "MDG", "450"),
    ("Malawi", "MW", "MWI", "454"),
    ("Malaysia", "MY", "MYS", "458", ["Malaysian", "Malaysien"]),
    ("Maldives", "MV", "MDV", "462"),
    ("Mali", "ML", "MLI", "466"),
    ("Malta", "MT", "MLT", "470", ["Maltese"]),
    ("Mauritania", "MR", "MRT", "478"),
    ("Mauritius", "MU", "MUS", "480"),
    ("Mexico", "MX", "MEX", "484", ["Mexican"]),
    ("Micronesia, Federated States of", "FM", "FSM", "583"),
    ("Moldova, Republic of", "MD", "MDA", "498", ["Moldovan"]),
    ("Monaco", "MC", "MCO", "492"),
    ("Mongolia", "MN", "MNG", "496"),
    ("Montenegro", "ME", "MNE", "499"),
    ("Morocco", "MA", "MAR", "504", ["Moroccan"]),
    ("Mozambique", "MZ", "MOZ", "508"),
    ("Myanmar", "MM", "MMR", "104"),
    ("Namibia", "NA", "NAM", "516", ["Namibian"]),
    ("Nauru", "NR", "NRU", "520"),
    ("Nepal", "NP", "NPL", "524"),
    ("Netherlands", "NL", "NLD", "528", ["Holland"]),
    ("New Zealand", "NZ", "NZL", "554", ["Kiwi", "New Zealander", "Aotearoa"]),
    ("Nicaragua", "NI", "NIC", "558", ["Nicaraguan"]),
    ("Niger", "NE", "NER", "562", ["Nigerien"]),
    ("Nigeria", "NG", "NGA", "566", ["Nigerian"]),
    ("Norway", "NO", "NOR", "578", ["Norwegian"]),
    ("Oman", "OM", "OMN", "512", ["Omani"]),
    ("Pakistan", "PK", "PAK", "586"),
    ("Palau", "PW", "PLW", "585"),
    ("Palestine, State of", "PS", "PSE", "275", ["Palestinian", "West Bank", "Gaza"]),
    ("Panama", "PA", "PAN", "591", ["Panaman"]),
    ("Papua New Guinea", "PG", "PNG", "598"),
    ("Paraguay", "PY", "PRY", "600", ["Paraguayan"]),
    ("Peru", "PE", "PER", "604", ["Peruvian", "Lima"]),
    ("Philippines", "PH", "PHL", "608"),
    ("Poland", "PL", "POL", "616"),
    ("Portugal", "PT", "PRT", "620"),
    ("Puerto Rico", "PR", "PRI", "630", ["Puerto Rican", "Boriqua"]),
    ("Qatar", "QA", "QAT", "634", ["Qatari"]),
    ("Romania", "RO", "ROU", "642"),
    ("Russia", "RU", "RUS", "643", ["Russian"]),
    ("Rwanda", "RW", "RWA", "646", ["Rwandan"]),
    ("Samoa", "WS", "WSM", "882"),
    ("San Marino", "SM", "SMR", "674"),
    ("Sao Tome and Principe", "ST", "STP", "678"),
    ("Saudi Arbia", "SA", "SAU", "682", ["Saudi", "Riyadh", "Jeddah", "Saudia"]),
    ("Senegal", "SN", "SEN", "686"),
    ("Serbia", "RS", "SRB", "688"),
    ("Seychelles", "SC", "SYC", "690"),
    ("Sierra Leone", "SL", "SLE", "694"),
    ("Singapore", "SG", "SGP", "702", ["Singaporean"]),
    ("Slovakia", "SK", "SVK", "703"),
    ("Slovenia", "SI", "SVN", "705"),
    ("Somalia", "SO", "SOM", "706", ["Somali", "Mogadishu"]),
    ("South Africa", "ZA", "ZAF", "710"),
    ("South Sudan", "SS", "SSD", "728"),
    ("Spain", "ES", "ESP", "724"),
    ("Sri Lanka", "LK", "LKA", "144", ["Ceylon"]),
    ("Sudan", "SD", "SDN", "729", ["Sudanese"]),
    ("Suriname", "SR", "SUR", "740", ["Surinamese"]),
    ("Swaziland", "SZ", "SWZ", "748"),
    ("Sweden", "SE", "SWE", "752", ["Swedish", "Svedish"]),
    ("Switzerland", "CH", "CHE", "756", ["Swiss", "Schweiz"]),
    ("Syria", "SY", "SYR", "760", ["Syrian", "Levant", "Al-sham"]),
    ("Taiwan, Province of China", "TW", "TWN", "158", ["Taiwanese", "Taipei"]),
    ("Tajikistan", "TJ", "TJK", "762"),
    ("Tanzania, United Republic of", "TZ", "TZA", "834", ["Tanzanian"]),
    ("Thailand", "TH", "THA", "764"),
    ("Timor-Leste", "TL", "TLS", "626", ["East Timor"]),
    ("Togo", "TG", "TGO", "768"),
    ("Tokelau", "TK", "TKL", "772"),
    ("Tonga", "TO", "TON", "776"),
    ("Trinidad and Tobago", "TT", "TTO", "780"),
    ("Tunisia", "TN", "TUN", "788", ["Tunisian"]),
    ("Turkey", "TR", "TUR", "792"),
    ("Turkmenistan", "TM", "TKM", "795"),
    ("Tuvalu", "TV", "TUV", "798"),
    ("Uganda", "UG", "UGA", "800", ["Ugandan"]),
    ("Ukraine", "UA", "UKR", "804", ["Ukrainian"]),
    ("United Arb Emirates", "AE", "ARE", "784", ["Dubai", "Abu Dhabi"]),
    ("United Kingdom", "GB", "GBR", "826", ["British", "England", "London"]),
    ("United Kingdom", "UK", "UKE", "826", ["British", "England", "London"]),
    ("United States", "US", "USA", "840", ["America", "Amerikaner", "American"]),
    ("Uruguay", "UY", "URY", "858", ["Uruguayan", "Montevideo"]),
    ("Uzbekistan", "UZ", "UZB", "860"),
    ("Vanuatu", "VU", "VUT", "548"),
    ("Venezuela", "VE", "VEN", "862", ["Venezuelan"]),
    ("Vietnam", "VN", "VNM", "704", ["Viet Nam"]),
    ("Kosovo", "XK", "XKK", "999", ["Kosovar"]),
    ("Yemen", "YE", "YEM", "887", ["Yemeni", "Sanaa"]),
    ("Zambia", "ZM", "ZMB", "894", ["Zambian"]),
    ("Zimbabwe", "ZW", "ZWE", "716"),
]

# Convert each tuple in the list to a named tuple
COUNTRY_LIST = [CountryTuple(*country_data) for country_data in countries]

# A dictionary with languages as keys and country codes as values.
ISO_LANGUAGE_COUNTRY_ASSOCIATED = {
    "ar-CY": "acy",
    "ar-DZ": "arq",
    "ar-BH": "abv",
    "ar-TD": "shu",
    "ar-EG": "arz",
    "ar-KW": "afb",
    "ar-IQ": "acm",
    "ar-AE": "afb",
    "ar-LB": "apc",
    "ar-SY": "apc",
    "ar-LY": "ayl",
    "ar-SA": "acw",
    "ar-OM": "acx",
    "ar-IL": "apc",
    "ar-PS": "apc",
    "ar-JO": "apc",
    "ar-SD": "apd",
    "ar-TN": "aeb",
    "ay-PE": "ayc",
    "ay-CL": "ayr",
    "ay-BO": "ayr",
    "de-CH": "gsw",
    "fa-AF": "prs",
    "ff-SN": "fuc",
    "ff-GM": "fuc",
    "ff-MR": "fuc",
    "ff-SL": "fuf",
    "ff-GN": "fuf",
    "ff-GH": "ffm",
    "ff-ML": "ffm",
    "ff-BJ": "fue",
    "ff-TG": "fue",
    "ff-BF": "fuh",
    "ff-NE": "fuh",
    "ff-NG": "fuv",
    "ff-CM": "fub",
    "ff-TD": "fub",
    "ff-SD": "fub",
    "ff-CF": "fui",
    "gn-BO": "gui",
    "hi-FJ": "hif",
    "om-KE": "gax",
    "ms-BN": "kxd",
    "sw-CD": "swc",
    "uz-AF": "uzs",
    "sq-XK": "aln",
}

ENGLISH_2_WORDS = [
    "Am",
    "An",
    "As",
    "Be",
    "Br",
    "El",
    "He",
    "Is",
    "It",
    "My",
    "No",
    "Or",
    "Se",
    "So",
    "To",
    "Tw",
]
ENGLISH_3_WORDS = [
    "Abs",
    "Abu",
    "Aby",
    "Ace",
    "Act",
    "Add",
    "Ado",
    "Ads",
    "Aft",
    "Age",
    "Ago",
    "Aid",
    "Ail",
    "Aim",
    "Air",
    "Ait",
    "Aka",
    "Ale",
    "Amp",
    "And",
    "Ant",
    "Ape",
    "App",
    "Apt",
    "Arc",
    "Are",
    "Ark",
    "Arm",
    "Art",
    "Ash",
    "Ask",
    "Asp",
    "Ass",
    "Ate",
    "Auk",
    "Awe",
    "Awl",
    "Awn",
    "Axe",
    "Azo",
    "Baa",
    "Bad",
    "Bag",
    "Bah",
    "Bam",
    "Ban",
    "Bar",
    "Bat",
    "Bay",
    "Bed",
    "Bee",
    "Beg",
    "Bet",
    "Bey",
    "Bib",
    "Bid",
    "Big",
    "Bin",
    "Bio",
    "Bit",
    "Boa",
    "Bob",
    "Bod",
    "Bog",
    "Boo",
    "Bop",
    "Bot",
    "Bow",
    "Box",
    "Boy",
    "Bra",
    "Bro",
    "Bub",
    "Bud",
    "Bug",
    "Bum",
    "Bun",
    "Bus",
    "But",
    "Buy",
    "Bye",
    "Cab",
    "Cad",
    "Cam",
    "Can",
    "Cap",
    "Car",
    "Cat",
    "Caw",
    "Cee",
    "Cha",
    "Chi",
    "Cob",
    "Cod",
    "Cog",
    "Com",
    "Con",
    "Coo",
    "Cop",
    "Cot",
    "Cow",
    "Cox",
    "Coy",
    "Cry",
    "Cub",
    "Cud",
    "Cue",
    "Cup",
    "Cur",
    "Cut",
    "Dab",
    "Dad",
    "Dag",
    "Dam",
    "Day",
    "Dee",
    "Den",
    "Dew",
    "Dib",
    "Did",
    "Die",
    "Dig",
    "Dim",
    "Din",
    "Dip",
    "Doc",
    "Doe",
    "Dog",
    "Don",
    "Doo",
    "Dop",
    "Dot",
    "Dry",
    "Dub",
    "Dud",
    "Due",
    "Dug",
    "Duh",
    "Dun",
    "Duo",
    "Dux",
    "Dye",
    "Ear",
    "Eat",
    "Ebb",
    "Eel",
    "Egg",
    "Ego",
    "Eke",
    "Elf",
    "Elk",
    "Elm",
    "Emo",
    "Emu",
    "End",
    "Eon",
    "Era",
    "Erg",
    "Err",
    "Ese",
    "Etc",
    "Eve",
    "Ewe",
    "Eye",
    "Fab",
    "Fad",
    "Fag",
    "Fan",
    "Far",
    "Far",
    "Fat",
    "Fax",
    "Fay",
    "Fed",
    "Fee",
    "Fen",
    "Few",
    "Fey",
    "Fez",
    "Fib",
    "Fie",
    "Fig",
    "Fin",
    "Fir",
    "Fit",
    "Fix",
    "Fly",
    "Fob",
    "Foe",
    "Fog",
    "Fon",
    "Fop",
    "For",
    "Fox",
    "Fry",
    "Fue",
    "Fun",
    "Fur",
    "Gab",
    "Gag",
    "Gak",
    "Gal",
    "Gap",
    "Gas",
    "Gaw",
    "Gay",
    "Gee",
    "Gel",
    "Gem",
    "Geo",
    "Get",
    "Gig",
    "Gil",
    "Gin",
    "Git",
    "Gnu",
    "Gob",
    "God",
    "Goo",
    "Got",
    "Gum",
    "Gun",
    "Gut",
    "Guy",
    "Gym",
    "Had",
    "Hag",
    "Hal",
    "Han",
    "Ham",
    "Has",
    "Hat",
    "Hay",
    "Hem",
    "Hen",
    "Her",
    "Hew",
    "Hex",
    "Hey",
    "Hid",
    "Him",
    "Hip",
    "His",
    "Hit",
    "Hoe",
    "Hog",
    "Hop",
    "Hot",
    "How",
    "Hoy",
    "Hub",
    "Hue",
    "Hug",
    "Hug",
    "Huh",
    "Hum",
    "Hut",
    "Ice",
    "Ich",
    "Ick",
    "Icy",
    "Ilk",
    "Ill",
    "Imp",
    "Ink",
    "Inn",
    "Ion",
    "Ire",
    "Irk",
    "Ism",
    "Its",
    "Jab",
    "Jag",
    "Jah",
    "Jak",
    "Jam",
    "Jar",
    "Jav",
    "Jaw",
    "Jay",
    "Jem",
    "Jet",
    "Jew",
    "Jib",
    "Jig",
    "Job",
    "Joe",
    "Jog",
    "Jon",
    "Jot",
    "Joy",
    "Jug",
    "Jus",
    "Jut",
    "Keg",
    "Key",
    "Kid",
    "Kin",
    "Kit",
    "Koa",
    "Kob",
    "Koi",
    "Lab",
    "Lad",
    "Lag",
    "Lap",
    "Law",
    "Lax",
    "Lay",
    "Lea",
    "Led",
    "Lee",
    "Leg",
    "Lei",
    "Let",
    "Lew",
    "Lid",
    "Lie",
    "Lip",
    "Lit",
    "Lob",
    "Log",
    "Lol",
    "Loo",
    "Lop",
    "Los",
    "Lot",
    "Low",
    "Lug",
    "Lux",
    "Lye",
    "Mac",
    "Mad",
    "Mag",
    "Man",
    "Mao",
    "Map",
    "Mar",
    "Mat",
    "Maw",
    "Max",
    "May",
    "Men",
    "Met",
    "Mex",
    "Mic",
    "Mid",
    "Min",
    "Mit",
    "Mix",
    "Mob",
    "Mod",
    "Mog",
    "Mom",
    "Mon",
    "Moo",
    "Mop",
    "Mow",
    "Mud",
    "Mug",
    "Mum",
    "Nab",
    "Nag",
    "Nap",
    "Nay",
    "Nee",
    "Neo",
    "Net",
    "New",
    "Nib",
    "Nil",
    "Nip",
    "Nit",
    "Nix",
    "Nob",
    "Nod",
    "Nog",
    "Non",
    "Nor",
    "Not",
    "Now",
    "Nub",
    "Nun",
    "Nut",
    "Oaf",
    "Oak",
    "Oar",
    "Oat",
    "Odd",
    "Ode",
    "Off",
    "Oft",
    "Ohm",
    "Oil",
    "Old",
    "Ole",
    "Oma",
    "One",
    "Opt",
    "Orb",
    "Ore",
    "Our",
    "Out",
    "Out",
    "Ova",
    "Owe",
    "Owl",
    "Own",
    "Pac",
    "Pad",
    "Pal",
    "Pan",
    "Pap",
    "Par",
    "Pas",
    "Pat",
    "Paw",
    "Pax",
    "Pay",
    "Pea",
    "Pee",
    "Peg",
    "Pen",
    "Pep",
    "Per",
    "Pet",
    "Pew",
    "Pls",
    "Plz",
    "Pic",
    "Pie",
    "Pig",
    "Pin",
    "Pip",
    "Pit",
    "Pix",
    "Ply",
    "Pod",
    "Poe",
    "Pog",
    "Poi",
    "Poo",
    "Pop",
    "Pot",
    "Pow",
    "Pox",
    "Pre",
    "Pro",
    "Pry",
    "Pub",
    "Pud",
    "Pug",
    "Pun",
    "Pup",
    "Pus",
    "Put",
    "Pyx",
    "Qat",
    "Qua",
    "Quo",
    "Rad",
    "Rag",
    "Ram",
    "Ran",
    "Rap",
    "Rat",
    "Raw",
    "Ray",
    "Red",
    "Rib",
    "Rid",
    "Rig",
    "Rim",
    "Rip",
    "Rob",
    "Roc",
    "Rod",
    "Roe",
    "Rot",
    "Row",
    "Rub",
    "Rue",
    "Rug",
    "Rum",
    "Run",
    "Rut",
    "Rye",
    "Sac",
    "Sad",
    "Sag",
    "Sap",
    "Sat",
    "Saw",
    "Sax",
    "Say",
    "Sea",
    "Sec",
    "See",
    "Set",
    "Sew",
    "Sex",
    "She",
    "Shh",
    "Shy",
    "Sic",
    "Sim",
    "Sin",
    "Sip",
    "Sir",
    "Sis",
    "Sit",
    "Six",
    "Ski",
    "Sky",
    "Sly",
    "Sob",
    "Sod",
    "Som",
    "Son",
    "Sop",
    "Sot",
    "Sow",
    "Soy",
    "Spa",
    "Spy",
    "Sty",
    "Sub",
    "Sue",
    "Sum",
    "Sun",
    "Sun",
    "Sup",
    "Tab",
    "Tad",
    "Tag",
    "Tam",
    "Tan",
    "Tae",
    "Tap",
    "Tar",
    "Tat",
    "Tax",
    "Tea",
    "Tee",
    "Ten",
    "The",
    "Thx",
    "Tic",
    "Tie",
    "Til",
    "Tin",
    "Tip",
    "Tit",
    "Toe",
    "Toe",
    "Tom",
    "Ton",
    "Too",
    "Top",
    "Tot",
    "Tow",
    "Toy",
    "Try",
    "Tub",
    "Tug",
    "Tui",
    "Tut",
    "Two",
    "Txt",
    "Ugh",
    "Uke",
    "Ump",
    "Urn",
    "Usa",
    "Use",
    "Van",
    "Vat",
    "Vee",
    "Vet",
    "Vex",
    "Via",
    "Vie",
    "Vig",
    "Vim",
    "Voe",
    "Vow",
    "Wad",
    "Wag",
    "Wan",
    "War",
    "Was",
    "Wax",
    "Way",
    "Web",
    "Wed",
    "Wee",
    "Wel",
    "Wen",
    "Wet",
    "Who",
    "Why",
    "Wig",
    "Win",
    "Wit",
    "Wiz",
    "Woe",
    "Wog",
    "Wok",
    "Won",
    "Woo",
    "Wow",
    "Wry",
    "Wwi",
    "Wye",
    "Yak",
    "Yam",
    "Yap",
    "Yaw",
    "Yay",
    "Yea",
    "Yen",
    "Yep",
    "Yes",
    "Yet",
    "Yew",
    "Yip",
    "You",
    "Yow",
    "Yum",
    "Yup",
    "Zag",
    "Zap",
    "Zed",
    "Zee",
    "Zen",
    "Zig",
    "Zip",
    "Zit",
    "Zoa",
    "Zoo",
]
