name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create dummy login file
      run: |
        echo "PASSWORD = ''" >> code/_login.py
        echo "USERNAME = ''" >> code/_login.py
        echo "ZIFANG_APP_ID = ''" >> code/_login.py
        echo "ZIFANG_APP_SECRET = ''" >> code/_login.py
        echo "ZIWEN_APP_ID = ''" >> code/_login.py
        echo "ZIWEN_APP_SECRET = ''" >> code/_login.py
    - name: Analysing the code with pylint
      run: |
        git ls-files '*.py' | grep -v '^tests/' | xargs pylint
